authors:
  Gaende:
    name: Gaende
    description: Project Owner
    avatar: https://avatars.githubusercontent.com/u/16535506?v=4
    url: https://x.com/gemboi_eth
  Cross0ver:
    name: Crossover
    description: Dev
    avatar: https://pbs.twimg.com/profile_images/1848803778809434113/-4bIEhM3_400x400.jpg
    url: https://x.com/Cross0verX/photo
  NT:
    name: Dev
    description: Expert Software Developper Team
    avatar: https://pbs.twimg.com/profile_images/1849271541026189312/zRR2JTUD_400x400.jpg
    url: https://x.com/nulltech_inc
